// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//---------------------------------------------------------------------------
// accuracy — characterizes each math engine (cordic / dbl / flt) against a
// long-double <cmath> reference, fpm-style. Reports max/mean error in units
// of the OUTPUT grid notch (an error < 0.5 notch means the engine returned
// the correctly rounded grid point). The long-double reference and <cmath>
// live only in this test harness — the library itself stays float-free on
// the cordic path.
//
//   ./beman.inside.accuracy             # markdown table to stdout
//   ./beman.inside.accuracy <file.md>   # write the table to <file.md>
//
// The `beman.inside.accuracy_report` CMake target regenerates docs/accuracy.md with it.
//---------------------------------------------------------------------------
#include <beman/inside/inside.hpp>
#include <beman/inside/cmath.hpp>

#include <cmath>
#include <cstdio>

using namespace beman::inside;

namespace
{
  // Exact value of an inside (or grid constant) as long double, via rational.
  long double to_long_double(detail::rational r)
  {
    return static_cast<long double>(r.Numerator)
         / static_cast<long double>(r.Denominator);
  }

  struct stats
  {
    long double max_err  = 0.0L;   // in output notches
    long double mean_err = 0.0L;
    long        samples  = 0;
  };

  // Sweeps `engine_fn` over the whole input grid (strided to ~`target_samples`
  // points) and accumulates the error against `reference_fn` in output-notch
  // units.
  template <typename In, typename EngineFn, typename ReferenceFn>
  stats sweep(EngineFn engine_fn, ReferenceFn reference_fn,
              long target_samples = 20000)
  {
    const long double lo        = to_long_double(Lower<In>);
    const long double in_notch  = to_long_double(Notch<In>);
    const long double span      = to_long_double(Upper<In>) - lo;
    const long        count     = static_cast<long>(span / in_notch);
    const long        stride    = count > target_samples ? count / target_samples : 1;

    stats s;
    long double sum = 0.0L;
    for (long i = 0; i <= count; i += stride)
    {
      const long double value = lo + static_cast<long double>(i) * in_notch;
      const In x{static_cast<double>(value)};

      // Some ops return expected<inside, errc> (runtime-failable domains);
      // unwrap and skip the rare out-of-domain sample.
      const auto outcome = engine_fn(x);
      constexpr bool failable =
          requires { outcome.has_value(); *outcome; };
      if constexpr (failable)
        if (!outcome.has_value())
          continue;
      const auto result = [&]{
        if constexpr (failable) return *outcome; else return outcome; }();
      const long double out_notch =
          to_long_double(Notch<std::remove_cv_t<decltype(result)>>);
      const long double err =
          std::fabs(to_long_double(detail::rational{result}) - reference_fn(value))
          / (out_notch > 0.0L ? out_notch : 1.0L);

      if (err > s.max_err) s.max_err = err;
      sum += err;
      ++s.samples;
    }
    s.mean_err = s.samples ? sum / static_cast<long double>(s.samples) : 0.0L;
    return s;
  }

  void row(std::FILE* out, const char* function, const char* engine,
           const char* domain, stats s)
  {
    std::fprintf(out, "| %-7s | %-6s | %-14s | %10.4Lf | %10.6Lf | %ld |\n",
                 function, engine, domain, s.max_err, s.mean_err, s.samples);
  }

  // Input grids — dyadic 2^-14 lattices with `f64` (f64) storage, the fp
  // engines' intended pairing: results snap through the fp store path. All
  // engines run the identical grids, so notch-unit errors compare 1:1.
  // (Integer-index snap grids also work — full-mantissa results store via the
  // 128-bit rounded path — but `f64` keeps the published table's store
  // semantics uniform across engines.)
  using angle_grid = inside<{{-8, 8},        notch<1, 16384>}, round_nearest | f64>;
  using tan_grid   = inside<{{-1.5, 1.5},   notch<1, 16384>}, round_nearest | f64>;
  using unit_grid  = inside<{{-1, 1},       notch<1, 16384>}, round_nearest | f64>;
  using sqrt_grid  = inside<{{0, 16},       notch<1, 16384>}, round_nearest | f64>;
  using log_grid   = inside<{{1, 1000},     notch<1, 16384>}, round_nearest | f64>;
}

int main(int argc, char** argv)
{
  std::FILE* out = stdout;
  if (argc > 1)
  {
    out = std::fopen(argv[1], "w");
    if (!out) { std::perror(argv[1]); return 1; }
  }

  std::fprintf(out,
    "# Engine accuracy\n\n"
    "Generated by `beman.inside.accuracy` (tests/beman/inside/accuracy.cpp) — do not edit by hand.\n"
    "Regenerate with `cmake --build <build-dir> --target beman.inside.accuracy_report` (configure with `-DBEMAN_INSIDE_BUILD_TOOLS=ON`).\n\n"
    "Error is measured against a long-double `<cmath>` reference, in units of\n"
    "the **output grid notch**: max < 0.5 means every sampled result is the\n"
    "correctly rounded grid point. Engines: `cordic` (integer/CORDIC, FPU-free,\n"
    "bit-exact everywhere), `dbl` (reproducible binary64), `flt` (binary32).\n"
    "See [math.md](math.md) for the engine model.\n\n"
    "| fn      | engine | domain         | max (notch) | mean (notch) | samples |\n"
    "|---------|--------|----------------|-------------|--------------|---------|\n");

  // One macro row per (function, grid, reference): expands to the three
  // engine namespaces so all engines run the identical sweep.
#define BEMAN_INSIDE_ACCURACY(fn, In, domain, ref)                                          \
  row(out, #fn, "cordic", domain,                                                  \
      sweep<In>([](In x){ return math::cordic::fn(x); },                           \
                [](long double v){ return ref; }));                                \
  row(out, #fn, "dbl", domain,                                                     \
      sweep<In>([](In x){ return math::dbl::fn(x); },                              \
                [](long double v){ return ref; }));                                \
  row(out, #fn, "flt", domain,                                                     \
      sweep<In>([](In x){ return math::flt::fn(x); },                              \
                [](long double v){ return ref; }));

  BEMAN_INSIDE_ACCURACY(sin,   angle_grid, "[-8, 8]",      sinl(v))
  BEMAN_INSIDE_ACCURACY(cos,   angle_grid, "[-8, 8]",      cosl(v))
  BEMAN_INSIDE_ACCURACY(tan,   tan_grid,   "[-1.5, 1.5]",  tanl(v))
  BEMAN_INSIDE_ACCURACY(asin,  unit_grid,  "[-1, 1]",      asinl(v))
  BEMAN_INSIDE_ACCURACY(acos,  unit_grid,  "[-1, 1]",      acosl(v))
  BEMAN_INSIDE_ACCURACY(atan,  angle_grid, "[-8, 8]",      atanl(v))
  BEMAN_INSIDE_ACCURACY(sinh,  angle_grid, "[-8, 8]",      sinhl(v))
  BEMAN_INSIDE_ACCURACY(cosh,  angle_grid, "[-8, 8]",      coshl(v))
  BEMAN_INSIDE_ACCURACY(tanh,  angle_grid, "[-8, 8]",      tanhl(v))
  BEMAN_INSIDE_ACCURACY(exp,   angle_grid, "[-8, 8]",      expl(v))
  BEMAN_INSIDE_ACCURACY(exp2,  angle_grid, "[-8, 8]",      exp2l(v))
  BEMAN_INSIDE_ACCURACY(log,   log_grid,   "[1, 1000]",    logl(v))
  BEMAN_INSIDE_ACCURACY(log2,  log_grid,   "[1, 1000]",    log2l(v))
  BEMAN_INSIDE_ACCURACY(log10, log_grid,   "[1, 1000]",    log10l(v))
  BEMAN_INSIDE_ACCURACY(sqrt,  sqrt_grid,  "[0, 16]",      sqrtl(v))
  BEMAN_INSIDE_ACCURACY(cbrt,  angle_grid, "[-8, 8]",      cbrtl(v))
#undef BEMAN_INSIDE_ACCURACY

  if (out != stdout) std::fclose(out);
  return 0;
}
